### ISSUE TITLE
Ruby Arrays

### ISSUE THREAD

**Issue by mmatongo** [cazterk/learn_ruby#1]
https://github.com/cazterk/learn_ruby/blob/6c7f737e50028e01c78de782aa78b3e750ee168f/5.arrays.rb#L28-L30

Alternatively
```rb
friends << "caz"
friends << "terk"
friends << "jim"
```

or
```rb
friends << "caz" << "terk" << "jim"
```

**Comment by cazterk** [comment]
Interesting will explore that in due time, just got started with ruby

**Comment by mmatongo** [comment]
https://github.com/cazterk/learn_ruby/blob/6c7f737e50028e01c78de782aa78b3e750ee168f/5.arrays.rb#L37

```rb
puts
```

creates a new line, its redundant adding one unless working with print.

**Comment by cazterk** [comment]
just puts ???

**Comment by mmatongo** [comment]
> just puts ???

Yes

**Comment by cazterk** [comment]
Interesting huh, anyways I'm new to the lang
