### ISSUE TITLE
Gets Chop

### ISSUE THREAD

**Issue by mmatongo** [cazterk/learn_ruby#2]
https://github.com/cazterk/learn_ruby/blob/2a93ab26237fc534b811345847b8d74d1f18d733/4.user_input.rb#L6-L8

You can cast types using `gets`
so 
```rb
 num1 = gets.chomp 
 puts "enter second number: " 
 num2 = gets.chomp 
```
can be
```rb
 num1 = gets.chomp.to_f
 puts "enter second number: " 
 num2 = gets.chomp.to_f
```

also experiment with `ARGV`

**Comment by cazterk** [comment]
Thank you man will see what I conjure up
