### ISSUE TITLE
Putting

### ISSUE THREAD

**Issue by mmatongo** [cazterk/learn_ruby#3]
https://github.com/cazterk/learn_ruby/blob/2a93ab26237fc534b811345847b8d74d1f18d733/8.dictionaries.rb#L12-L15

or
```rb
test_grades.each { |key, value| puts "\t #{key}) #{value}" }
```

**Comment by cazterk** [comment]
Does that work the same?

**Comment by mmatongo** [comment]
> Does that work the same?

To a degree

**Comment by cazterk** [comment]
Cool stuff 🤜🏼🤛🏽
